apiVersion: v2
name: lan-party
description: Mercurius LAN party backend, frontend and CloudNativePG database
type: application
version: 2.0.0
home: https://github.com/MercuriusAalst/lan-party-helmchart
maintainers:
  - name: Mercurius Aalst
